test:
  testtext: CONFIG_IS_HERE

server:
  port: 8088

config-server:
  route: localhost:8888

service-registry:
  route: localhost:8761

spring:
  config:
    import: configserver:http://root:test@${config-server.route}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-3b-fh-41c4.a.aivencloud.com:20557/defaultdb?sslMode=REQUIRED
    username: avnadmin
    password: AVNS_oLeNCKj9lV4WKoo4itV
  application:
    name: rest-api

springdoc:
  api-docs:
    path: /rest-api-docs
  swagger-ui:
    enabled: false


eureka:
  client:
    serviceUrl:
      defaultZone: http://${service-registry.route}/eureka/

